// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: demo.proto

package hipstershop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BasketLedger_AddItem_FullMethodName   = "/hipstershop.BasketLedger/AddItem"
	BasketLedger_GetCart_FullMethodName   = "/hipstershop.BasketLedger/GetCart"
	BasketLedger_EmptyCart_FullMethodName = "/hipstershop.BasketLedger/EmptyCart"
)

// BasketLedgerClient is the client API for BasketLedger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BasketLedgerClient interface {
	AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*Empty, error)
	GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*Cart, error)
	EmptyCart(ctx context.Context, in *EmptyCartRequest, opts ...grpc.CallOption) (*Empty, error)
}

type basketLedgerClient struct {
	cc grpc.ClientConnInterface
}

func NewBasketLedgerClient(cc grpc.ClientConnInterface) BasketLedgerClient {
	return &basketLedgerClient{cc}
}

func (c *basketLedgerClient) AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BasketLedger_AddItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketLedgerClient) GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*Cart, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cart)
	err := c.cc.Invoke(ctx, BasketLedger_GetCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketLedgerClient) EmptyCart(ctx context.Context, in *EmptyCartRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BasketLedger_EmptyCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasketLedgerServer is the server API for BasketLedger service.
// All implementations must embed UnimplementedBasketLedgerServer
// for forward compatibility.
type BasketLedgerServer interface {
	AddItem(context.Context, *AddItemRequest) (*Empty, error)
	GetCart(context.Context, *GetCartRequest) (*Cart, error)
	EmptyCart(context.Context, *EmptyCartRequest) (*Empty, error)
	mustEmbedUnimplementedBasketLedgerServer()
}

// UnimplementedBasketLedgerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBasketLedgerServer struct{}

func (UnimplementedBasketLedgerServer) AddItem(context.Context, *AddItemRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItem not implemented")
}
func (UnimplementedBasketLedgerServer) GetCart(context.Context, *GetCartRequest) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCart not implemented")
}
func (UnimplementedBasketLedgerServer) EmptyCart(context.Context, *EmptyCartRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyCart not implemented")
}
func (UnimplementedBasketLedgerServer) mustEmbedUnimplementedBasketLedgerServer() {}
func (UnimplementedBasketLedgerServer) testEmbeddedByValue()                     {}

// UnsafeBasketLedgerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BasketLedgerServer will
// result in compilation errors.
type UnsafeBasketLedgerServer interface {
	mustEmbedUnimplementedBasketLedgerServer()
}

func RegisterBasketLedgerServer(s grpc.ServiceRegistrar, srv BasketLedgerServer) {
	// If the following call pancis, it indicates UnimplementedBasketLedgerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BasketLedger_ServiceDesc, srv)
}

func _BasketLedger_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketLedgerServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketLedger_AddItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketLedgerServer).AddItem(ctx, req.(*AddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketLedger_GetCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketLedgerServer).GetCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketLedger_GetCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketLedgerServer).GetCart(ctx, req.(*GetCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketLedger_EmptyCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketLedgerServer).EmptyCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketLedger_EmptyCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketLedgerServer).EmptyCart(ctx, req.(*EmptyCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BasketLedger_ServiceDesc is the grpc.ServiceDesc for BasketLedger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BasketLedger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.BasketLedger",
	HandlerType: (*BasketLedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItem",
			Handler:    _BasketLedger_AddItem_Handler,
		},
		{
			MethodName: "GetCart",
			Handler:    _BasketLedger_GetCart_Handler,
		},
		{
			MethodName: "EmptyCart",
			Handler:    _BasketLedger_EmptyCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

const (
	Suggestr_ListRecommendations_FullMethodName = "/hipstershop.Suggestr/ListRecommendations"
)

// SuggestrClient is the client API for Suggestr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SuggestrClient interface {
	ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error)
}

type suggestrSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewSuggestrClient(cc grpc.ClientConnInterface) SuggestrClient {
	return &suggestrSvcClient{cc}
}

func (c *suggestrSvcClient) ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecommendationsResponse)
	err := c.cc.Invoke(ctx, Suggestr_ListRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuggestrServer is the server API for Suggestr service.
// All implementations must embed UnimplementedSuggestrServer
// for forward compatibility.
type SuggestrServer interface {
	ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error)
	mustEmbedUnimplementedSuggestrServer()
}

// UnimplementedSuggestrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSuggestrServer struct{}

func (UnimplementedSuggestrServer) ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecommendations not implemented")
}
func (UnimplementedSuggestrServer) mustEmbedUnimplementedSuggestrServer() {}
func (UnimplementedSuggestrServer) testEmbeddedByValue()                               {}

// UnsafeSuggestrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuggestrServer will
// result in compilation errors.
type UnsafeSuggestrServer interface {
	mustEmbedUnimplementedSuggestrServer()
}

func RegisterSuggestrServer(s grpc.ServiceRegistrar, srv SuggestrServer) {
	// If the following call pancis, it indicates UnimplementedSuggestrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Suggestr_ServiceDesc, srv)
}

func _Suggestr_ListRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestrServer).ListRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Suggestr_ListRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestrServer).ListRecommendations(ctx, req.(*ListRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Suggestr_ServiceDesc is the grpc.ServiceDesc for Suggestr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Suggestr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.Suggestr",
	HandlerType: (*SuggestrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRecommendations",
			Handler:    _Suggestr_ListRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

const (
	CatalogVault_ListProducts_FullMethodName   = "/hipstershop.CatalogVault/ListProducts"
	CatalogVault_GetProduct_FullMethodName     = "/hipstershop.CatalogVault/GetProduct"
	CatalogVault_SearchProducts_FullMethodName = "/hipstershop.CatalogVault/SearchProducts"
)

// CatalogVaultClient is the client API for CatalogVault service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogVaultClient interface {
	ListProducts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListProductsResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error)
	SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error)
}

type catalogVaultClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogVaultClient(cc grpc.ClientConnInterface) CatalogVaultClient {
	return &catalogVaultClient{cc}
}

func (c *catalogVaultClient) ListProducts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, CatalogVault_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogVaultClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, CatalogVault_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogVaultClient) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResponse)
	err := c.cc.Invoke(ctx, CatalogVault_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogVaultServer is the server API for CatalogVault service.
// All implementations must embed UnimplementedCatalogVaultServer
// for forward compatibility.
type CatalogVaultServer interface {
	ListProducts(context.Context, *Empty) (*ListProductsResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error)
	mustEmbedUnimplementedCatalogVaultServer()
}

// UnimplementedCatalogVaultServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogVaultServer struct{}

func (UnimplementedCatalogVaultServer) ListProducts(context.Context, *Empty) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedCatalogVaultServer) GetProduct(context.Context, *GetProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedCatalogVaultServer) SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedCatalogVaultServer) mustEmbedUnimplementedCatalogVaultServer() {}
func (UnimplementedCatalogVaultServer) testEmbeddedByValue()                               {}

// UnsafeCatalogVaultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogVaultServer will
// result in compilation errors.
type UnsafeCatalogVaultServer interface {
	mustEmbedUnimplementedCatalogVaultServer()
}

func RegisterCatalogVaultServer(s grpc.ServiceRegistrar, srv CatalogVaultServer) {
	// If the following call pancis, it indicates UnimplementedCatalogVaultServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogVault_ServiceDesc, srv)
}

func _CatalogVault_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogVaultServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogVault_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogVaultServer).ListProducts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogVault_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogVaultServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogVault_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogVaultServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogVault_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogVaultServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogVault_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogVaultServer).SearchProducts(ctx, req.(*SearchProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogVault_ServiceDesc is the grpc.ServiceDesc for CatalogVault service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogVault_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.CatalogVault",
	HandlerType: (*CatalogVaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProducts",
			Handler:    _CatalogVault_ListProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _CatalogVault_GetProduct_Handler,
		},
		{
			MethodName: "SearchProducts",
			Handler:    _CatalogVault_SearchProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

const (
	FreightQuote_GetQuote_FullMethodName  = "/hipstershop.FreightQuote/GetQuote"
	FreightQuote_ShipOrder_FullMethodName = "/hipstershop.FreightQuote/ShipOrder"
)

// FreightQuoteClient is the client API for FreightQuote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FreightQuoteClient interface {
	GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error)
	ShipOrder(ctx context.Context, in *ShipOrderRequest, opts ...grpc.CallOption) (*ShipOrderResponse, error)
}

type freightQuoteClient struct {
	cc grpc.ClientConnInterface
}

func NewFreightQuoteClient(cc grpc.ClientConnInterface) FreightQuoteClient {
	return &freightQuoteClient{cc}
}

func (c *freightQuoteClient) GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuoteResponse)
	err := c.cc.Invoke(ctx, FreightQuote_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightQuoteClient) ShipOrder(ctx context.Context, in *ShipOrderRequest, opts ...grpc.CallOption) (*ShipOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipOrderResponse)
	err := c.cc.Invoke(ctx, FreightQuote_ShipOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreightQuoteServer is the server API for FreightQuote service.
// All implementations must embed UnimplementedFreightQuoteServer
// for forward compatibility.
type FreightQuoteServer interface {
	GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error)
	ShipOrder(context.Context, *ShipOrderRequest) (*ShipOrderResponse, error)
	mustEmbedUnimplementedFreightQuoteServer()
}

// UnimplementedFreightQuoteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFreightQuoteServer struct{}

func (UnimplementedFreightQuoteServer) GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedFreightQuoteServer) ShipOrder(context.Context, *ShipOrderRequest) (*ShipOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShipOrder not implemented")
}
func (UnimplementedFreightQuoteServer) mustEmbedUnimplementedFreightQuoteServer() {}
func (UnimplementedFreightQuoteServer) testEmbeddedByValue()                         {}

// UnsafeFreightQuoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FreightQuoteServer will
// result in compilation errors.
type UnsafeFreightQuoteServer interface {
	mustEmbedUnimplementedFreightQuoteServer()
}

func RegisterFreightQuoteServer(s grpc.ServiceRegistrar, srv FreightQuoteServer) {
	// If the following call pancis, it indicates UnimplementedFreightQuoteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FreightQuote_ServiceDesc, srv)
}

func _FreightQuote_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreightQuoteServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreightQuote_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreightQuoteServer).GetQuote(ctx, req.(*GetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreightQuote_ShipOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreightQuoteServer).ShipOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreightQuote_ShipOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreightQuoteServer).ShipOrder(ctx, req.(*ShipOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FreightQuote_ServiceDesc is the grpc.ServiceDesc for FreightQuote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FreightQuote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.FreightQuote",
	HandlerType: (*FreightQuoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _FreightQuote_GetQuote_Handler,
		},
		{
			MethodName: "ShipOrder",
			Handler:    _FreightQuote_ShipOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

const (
	FxRates_GetSupportedCurrencies_FullMethodName = "/hipstershop.FxRates/GetSupportedCurrencies"
	FxRates_Convert_FullMethodName                = "/hipstershop.FxRates/Convert"
)

// FxRatesClient is the client API for FxRates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FxRatesClient interface {
	GetSupportedCurrencies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSupportedCurrenciesResponse, error)
	Convert(ctx context.Context, in *CurrencyConversionRequest, opts ...grpc.CallOption) (*Money, error)
}

type fxRatesClient struct {
	cc grpc.ClientConnInterface
}

func NewFxRatesClient(cc grpc.ClientConnInterface) FxRatesClient {
	return &fxRatesClient{cc}
}

func (c *fxRatesClient) GetSupportedCurrencies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSupportedCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportedCurrenciesResponse)
	err := c.cc.Invoke(ctx, FxRates_GetSupportedCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxRatesClient) Convert(ctx context.Context, in *CurrencyConversionRequest, opts ...grpc.CallOption) (*Money, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Money)
	err := c.cc.Invoke(ctx, FxRates_Convert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FxRatesServer is the server API for FxRates service.
// All implementations must embed UnimplementedFxRatesServer
// for forward compatibility.
type FxRatesServer interface {
	GetSupportedCurrencies(context.Context, *Empty) (*GetSupportedCurrenciesResponse, error)
	Convert(context.Context, *CurrencyConversionRequest) (*Money, error)
	mustEmbedUnimplementedFxRatesServer()
}

// UnimplementedFxRatesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFxRatesServer struct{}

func (UnimplementedFxRatesServer) GetSupportedCurrencies(context.Context, *Empty) (*GetSupportedCurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportedCurrencies not implemented")
}
func (UnimplementedFxRatesServer) Convert(context.Context, *CurrencyConversionRequest) (*Money, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedFxRatesServer) mustEmbedUnimplementedFxRatesServer() {}
func (UnimplementedFxRatesServer) testEmbeddedByValue()                         {}

// UnsafeFxRatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FxRatesServer will
// result in compilation errors.
type UnsafeFxRatesServer interface {
	mustEmbedUnimplementedFxRatesServer()
}

func RegisterFxRatesServer(s grpc.ServiceRegistrar, srv FxRatesServer) {
	// If the following call pancis, it indicates UnimplementedFxRatesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FxRates_ServiceDesc, srv)
}

func _FxRates_GetSupportedCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxRatesServer).GetSupportedCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FxRates_GetSupportedCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxRatesServer).GetSupportedCurrencies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxRates_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrencyConversionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxRatesServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FxRates_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxRatesServer).Convert(ctx, req.(*CurrencyConversionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FxRates_ServiceDesc is the grpc.ServiceDesc for FxRates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FxRates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.FxRates",
	HandlerType: (*FxRatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupportedCurrencies",
			Handler:    _FxRates_GetSupportedCurrencies_Handler,
		},
		{
			MethodName: "Convert",
			Handler:    _FxRates_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

const (
	PayGuard_Charge_FullMethodName = "/hipstershop.PayGuard/Charge"
)

// PayGuardClient is the client API for PayGuard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayGuardClient interface {
	Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error)
}

type payGuardClient struct {
	cc grpc.ClientConnInterface
}

func NewPayGuardClient(cc grpc.ClientConnInterface) PayGuardClient {
	return &payGuardClient{cc}
}

func (c *payGuardClient) Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChargeResponse)
	err := c.cc.Invoke(ctx, PayGuard_Charge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayGuardServer is the server API for PayGuard service.
// All implementations must embed UnimplementedPayGuardServer
// for forward compatibility.
type PayGuardServer interface {
	Charge(context.Context, *ChargeRequest) (*ChargeResponse, error)
	mustEmbedUnimplementedPayGuardServer()
}

// UnimplementedPayGuardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayGuardServer struct{}

func (UnimplementedPayGuardServer) Charge(context.Context, *ChargeRequest) (*ChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Charge not implemented")
}
func (UnimplementedPayGuardServer) mustEmbedUnimplementedPayGuardServer() {}
func (UnimplementedPayGuardServer) testEmbeddedByValue()                        {}

// UnsafePayGuardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayGuardServer will
// result in compilation errors.
type UnsafePayGuardServer interface {
	mustEmbedUnimplementedPayGuardServer()
}

func RegisterPayGuardServer(s grpc.ServiceRegistrar, srv PayGuardServer) {
	// If the following call pancis, it indicates UnimplementedPayGuardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayGuard_ServiceDesc, srv)
}

func _PayGuard_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayGuardServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayGuard_Charge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayGuardServer).Charge(ctx, req.(*ChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayGuard_ServiceDesc is the grpc.ServiceDesc for PayGuard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayGuard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.PayGuard",
	HandlerType: (*PayGuardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _PayGuard_Charge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

const (
	MailCourier_SendOrderConfirmation_FullMethodName = "/hipstershop.MailCourier/SendOrderConfirmation"
)

// MailCourierClient is the client API for MailCourier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailCourierClient interface {
	SendOrderConfirmation(ctx context.Context, in *SendOrderConfirmationRequest, opts ...grpc.CallOption) (*Empty, error)
}

type mailCourierClient struct {
	cc grpc.ClientConnInterface
}

func NewMailCourierClient(cc grpc.ClientConnInterface) MailCourierClient {
	return &mailCourierClient{cc}
}

func (c *mailCourierClient) SendOrderConfirmation(ctx context.Context, in *SendOrderConfirmationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MailCourier_SendOrderConfirmation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailCourierServer is the server API for MailCourier service.
// All implementations must embed UnimplementedMailCourierServer
// for forward compatibility.
type MailCourierServer interface {
	SendOrderConfirmation(context.Context, *SendOrderConfirmationRequest) (*Empty, error)
	mustEmbedUnimplementedMailCourierServer()
}

// UnimplementedMailCourierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailCourierServer struct{}

func (UnimplementedMailCourierServer) SendOrderConfirmation(context.Context, *SendOrderConfirmationRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOrderConfirmation not implemented")
}
func (UnimplementedMailCourierServer) mustEmbedUnimplementedMailCourierServer() {}
func (UnimplementedMailCourierServer) testEmbeddedByValue()                      {}

// UnsafeMailCourierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailCourierServer will
// result in compilation errors.
type UnsafeMailCourierServer interface {
	mustEmbedUnimplementedMailCourierServer()
}

func RegisterMailCourierServer(s grpc.ServiceRegistrar, srv MailCourierServer) {
	// If the following call pancis, it indicates UnimplementedMailCourierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailCourier_ServiceDesc, srv)
}

func _MailCourier_SendOrderConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOrderConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailCourierServer).SendOrderConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailCourier_SendOrderConfirmation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailCourierServer).SendOrderConfirmation(ctx, req.(*SendOrderConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailCourier_ServiceDesc is the grpc.ServiceDesc for MailCourier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailCourier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.MailCourier",
	HandlerType: (*MailCourierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOrderConfirmation",
			Handler:    _MailCourier_SendOrderConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

const (
	OrderForge_PlaceOrder_FullMethodName = "/hipstershop.OrderForge/PlaceOrder"
)

// OrderForgeClient is the client API for OrderForge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderForgeClient interface {
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
}

type orderForgeClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderForgeClient(cc grpc.ClientConnInterface) OrderForgeClient {
	return &orderForgeClient{cc}
}

func (c *orderForgeClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, OrderForge_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderForgeServer is the server API for OrderForge service.
// All implementations must embed UnimplementedOrderForgeServer
// for forward compatibility.
type OrderForgeServer interface {
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	mustEmbedUnimplementedOrderForgeServer()
}

// UnimplementedOrderForgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderForgeServer struct{}

func (UnimplementedOrderForgeServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedOrderForgeServer) mustEmbedUnimplementedOrderForgeServer() {}
func (UnimplementedOrderForgeServer) testEmbeddedByValue()                         {}

// UnsafeOrderForgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderForgeServer will
// result in compilation errors.
type UnsafeOrderForgeServer interface {
	mustEmbedUnimplementedOrderForgeServer()
}

func RegisterOrderForgeServer(s grpc.ServiceRegistrar, srv OrderForgeServer) {
	// If the following call pancis, it indicates UnimplementedOrderForgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderForge_ServiceDesc, srv)
}

func _OrderForge_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderForgeServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderForge_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderForgeServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderForge_ServiceDesc is the grpc.ServiceDesc for OrderForge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderForge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.OrderForge",
	HandlerType: (*OrderForgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _OrderForge_PlaceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

const (
	PromoBeam_GetAds_FullMethodName = "/hipstershop.PromoBeam/GetAds"
)

// PromoBeamClient is the client API for PromoBeam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromoBeamClient interface {
	GetAds(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error)
}

type promoBeamClient struct {
	cc grpc.ClientConnInterface
}

func NewPromoBeamClient(cc grpc.ClientConnInterface) PromoBeamClient {
	return &promoBeamClient{cc}
}

func (c *promoBeamClient) GetAds(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdResponse)
	err := c.cc.Invoke(ctx, PromoBeam_GetAds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromoBeamServer is the server API for PromoBeam service.
// All implementations must embed UnimplementedPromoBeamServer
// for forward compatibility.
type PromoBeamServer interface {
	GetAds(context.Context, *AdRequest) (*AdResponse, error)
	mustEmbedUnimplementedPromoBeamServer()
}

// UnimplementedPromoBeamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromoBeamServer struct{}

func (UnimplementedPromoBeamServer) GetAds(context.Context, *AdRequest) (*AdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAds not implemented")
}
func (UnimplementedPromoBeamServer) mustEmbedUnimplementedPromoBeamServer() {}
func (UnimplementedPromoBeamServer) testEmbeddedByValue()                   {}

// UnsafePromoBeamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromoBeamServer will
// result in compilation errors.
type UnsafePromoBeamServer interface {
	mustEmbedUnimplementedPromoBeamServer()
}

func RegisterPromoBeamServer(s grpc.ServiceRegistrar, srv PromoBeamServer) {
	// If the following call pancis, it indicates UnimplementedPromoBeamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromoBeam_ServiceDesc, srv)
}

func _PromoBeam_GetAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoBeamServer).GetAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoBeam_GetAds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoBeamServer).GetAds(ctx, req.(*AdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromoBeam_ServiceDesc is the grpc.ServiceDesc for PromoBeam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromoBeam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.PromoBeam",
	HandlerType: (*PromoBeamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAds",
			Handler:    _PromoBeam_GetAds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
